# Generated by Django 2.2.3 on 2019-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_confirm',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
