# Generated by Django 2.2.3 on 2019-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_users_password_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
    ]
