# Generated by Django 2.2.3 on 2019-07-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_basketball'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
