# Generated by Django 2.2.3 on 2019-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolleyball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rugby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
    ]
