# Generated by Django 2.2.3 on 2019-08-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_bolleyball_rugby_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclisme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
    ]
