# Generated by Django 2.2.3 on 2019-08-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_cyclisme'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketball',
            name='la_mise',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='bolleyball',
            name='la_mise',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='cyclisme',
            name='la_mise',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='football',
            name='la_mise',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='rugby',
            name='la_mise',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='running',
            name='la_mise',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
